classes_by_week:
    pattern: /facilities/{facility}/{week}/classes
    defaults: { _controller: SCSSCourseBundle:SCSSClass:index }
classes_by_period:
    pattern: /facilities/{facility}/{week}/{period}/classes
    defaults: { _controller: SCSSCourseBundle:SCSSClass:index }
class_show:
    pattern: /facilities/{facility}/classes/{class}
    defaults: { _controller: SCSSCourseBundle:SCSSClass:show }
