parameters:
#    SCSS_report.example.class: SCSS\ReportBundle\Example

services:
#    SCSS_report.example:
#        class: %SCSS_report.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
