parameters:
#    SCSS_organization.example.class: SCSS\OrganizationBundle\Example

services:
#    SCSS_organization.example:
#        class: %SCSS_organization.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
