troop:
  class: sfDoctrineRouteCollection
  options:
    model: ScssTroop
    module: troop
    prefix_path: /troops/:district_slug
    column: troop_slug
#troops_by_country:
#troops_by_zone:
troops_by_district:
  url: /troops/:district_slug
  params: { module: troop, action: index }
troops_by_camp:
  url: /camps/:district_slug/:camp_slug/troops
  params: { module: troop, action: index }
