parameters:
################################################################################
## PUGX
################################################################################
    pugx_user_discriminator_parameters:
        classes:
            attendee:
                entity: Scss\OrganizationBundle\Entity\Attendee
                registration: Scss\OrganizationBundle\Form\Type\AttendeeType
                profile: Scss\OrganizationBundle\Form\Type\AttendeeType
                factory:
            passel_leader:
                entity: Scss\OrganizationBundle\Entity\PasselLeader
                registration: Scss\OrganizationBundle\Form\Type\PasselLeaderType
                profile: Scss\OrganizationBundle\Form\Type\PasselLeaderType
                factory:
            faculty:
                entity: Scss\FacilityBundle\Entity\Faculty
                registration: Scss\FacilityBundle\Form\Type\FacultyType
                profile: Scss\FacilityBundle\Form\Type\FacultyType
                factory: