parameters:
#    scss_user.example.class: Scss\UserBundle\Example

services:
    scss_user.registration.form.type:
        class: Scss\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: scss_user_registration }
#    my.facebook.user:
#        class: Scss\UserBundle\Security\User\Provider\FacebookProvider
#        arguments:
#            facebook: "@fos_facebook.api"
#            userManager: "@fos_user.user_manager"
#            validator: "@validator"
#            container: "@service_container"
