parameters:
#    SCSS_user.example.class: SCSS\UserBundle\Example

services:
#    SCSS_user.example:
#        class: %SCSS_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
