parameters:
#    scss_user.example.class: Scss\UserBundle\Example

services:
#    my.facebook.user:
#        class: Scss\UserBundle\Security\User\Provider\FacebookProvider
#        arguments:
#            facebook: "@fos_facebook.api"
#            userManager: "@fos_user.user_manager"
#            validator: "@validator"
#            container: "@service_container"
