# default values
all:
  avatar_default_img: /images/user_files/logos/avatar/default.png
  avatar_height: 50px
  avatar_width: 50px
  max_items_on_index: 10
  max_items_on_dashboard: 4
  min_periods_per_week: 3
  tte_periods_per_week: 7
  patrol_upload_logo_dir: /images/user_files/logos/patrol
  avatar_upload_dir: /images/user_files/logos/avatar
  autofill_class_search_max: 20
  menu_file: menu.yml
  facebook:
    api_key: 173494226064106
    api_secret: 41fbd98aa2efaeb12b2602149710ca86
    api_id: 173494226064106
    redirect_after_connect: true
    redirect_after_connect_url: '@dashboard'
    connect_signin_url: 'sfFacebookConnectAuth/signin'
    app_url: '/scss'
    guard_adapter: ~
    js_framework: jQuery # none, jQuery or prototype.
    # It is highly recommended to use a js framework if you want a correct experience in IE
  sf_guard_plugin:
    profile_class: sfGuardUserProfile
    profile_field_name: user_id
    profile_facebook_uid_name: facebook_uid # WARNING this column must be of type bigint ! 100000398093902 is a valid uid for example !
    profile_email_name: email
    profile_email_hash_name: email_hash
  facebook_connect:
    load_routing:     true
    user_permissions: []
  ddToggleSwitchPlugin:
    include_js: false
    js_path: /js
  lightbox:
    width: 900    # default width   - trailing p == percent, no p == px
    height: 580   # default height  - trailing p == percent, no p == px
    modal: false  # use modal    