imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false
    
web_profiler_extra:
    routing:    true
    container:  true
    assetic:    true
    twig:       true    

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true

security:
    firewalls:
        public:
            fos_facebook:
                app_url: "http://apps.facebook.com/scss/"
                server_url: "http://scss2.daviddurost.net/app_dev.php/"  