imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
#    assets_version: SomeVersionScheme
    default_locale:  %locale%
    session: ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
#        types:
#            enum: Scss\FacilityBundle\DBAL\Types\EnumType
#            quartersEnum: Scss\FacilityBundle\DBAL\Types\EnumQuartersType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

# FOS
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Scss\UserBundle\Entity\User
    

    
# JMS
jms_security_extra:
    # Whether you want to secure all services (true), or only secure specific
    # services (false); see also below
    secure_all_services: false

    # Enabling this setting will add an additional special attribute "IS_IDDQD".
    # Anybody with this attribute will effectively bypass all security checks.
    enable_iddqd_attribute: false

    # Enables expression language
    expressions: false

    # Allows you to disable some, or all built-in voters
    voters:
        disable_authenticated: false
        disable_role:          false
        disable_acl:           false

    # Allows you to specify access control rules for specific methods, such
    # as controller actions
    method_access_control: { }    
jms_aop:
    cache_dir: %kernel.cache_dir%/jms_aop  

knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default
    
fos_facebook:
    file:   %kernel.root_dir%/../vendor/facebook/php-sdk/src/base_facebook.php
    alias:  facebook
    secret: 41fbd98aa2efaeb12b2602149710ca86
    app_id: 173494226064106
    cookie: true
    permissions: [email, user_birthday, user_location]    
    
hwi_oauth:
    firewall_name: secured_area
    
    resource_owners:
        facebook:
            type: facebook
            client_id: 173494226064106
            client_secret: 41fbd98aa2efaeb12b2602149710ca86
            scope: ""
        google:
            type: google
            client_id: 986620454264.apps.googleusercontent.com
            client_secret: 2D_1VRUM65dAvIZfgrjsB9Ha
            scope: "https://www.googleapis.com/auth/plus.me"
        linkedin:
            type: linkedin
            client_id: wq7ouwedcs6f
            client_secret: E313GhN9FrgksrAT
            scope: ""
#        github:
#            type: github
#            client_id: 
#            client_secret:
#            scope: ""
        foursquare:
            type: foursquare
            client_id: ZWMV20TQ5ASWTHXOMPVET54TNFMMGQ4WGCEYTSEZWP2QXQFN
            client_secret: LHY4IZQGXBF0GLPMR2L21V3LDOETXYLWLP4CMB0H5ITDKL4D
            scope: ""
    fosub:
        username_iterations: 30
        properties:
#            github: githubId
            google: googleId
            facebook: facebookId
            foursquare: foursquareId
            linkedin: linkedinId
    connect: ~
    http_client:
        timeout:  5
        verify_peer: true
        ignore_errors: true
        max_redirects: 5