imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
#    assets_version: SomeVersionScheme
    default_locale:  %locale%
    session: ~

################################################################################
## Twig Configuration
################################################################################
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - "BraincraftedBootstrapBundle:Form:form_div_layout.html.twig"
            - 'OhGoogleMapFormTypeBundle:Form:fields.html.twig'

################################################################################
## Assetic Configuration
################################################################################
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~

################################################################################
## Doctrine Configuration
################################################################################
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        mapping_types:
            enum: string
            set: string
            varbinary: string
            tinyblob: text        
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false

################################################################################
## Doctrine Extensions
################################################################################
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default: 
          timestampable: true
          sluggable: true                        

################################################################################
## Swiftmailer Configuration
################################################################################
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

################################################################################
## FOS
################################################################################
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Scss\UserBundle\Entity\User
    service:
        user_manager: pugx_user_manager
    registration:
        form:
            handler: pugx_user_registration_form_handler
    profile:
        form:
            handler: pugx_user_profile_form_handler
    
################################################################################
## JMS
################################################################################
jms_security_extra:
#    secure_controllers:  true
    secure_all_services: false
    enable_iddqd_attribute: false
    expressions: false
    voters:
        disable_authenticated: false
        disable_role:          false
        disable_acl:           false
    method_access_control: { }    
jms_aop:
    cache_dir: %kernel.cache_dir%/jms_aop  

################################################################################
## KnP
################################################################################
knp_menu:
    twig: 
        template: ScssUserBundle:Base:menu.html.twig
    templating: false 
    default_renderer: twig      
    
################################################################################
## Google Maps
################################################################################
ivory_google_map:
    map:
      prefix_javascript_variable: "map_"
      html_container: "map"
      async: false
      auto_zoom: false
      center:
          longitude:  0
          latitude:   0
          no_wrap:    true
      zoom: 3
      bound:
          south_west:
              latitude:   -2.1
              longitude:  1.4
              no_wrap:    true
          north_east:
              latitude:   2.6
              longitude:  1.4
              no_wrap:    true
      type: "roadmap" 
      width:  "100%"
      height: "100%"
      map_options:
          disableDefaultUI:       true
          disableDoubleClickZoom: true
      stylesheet_options: 
          position: "absolute"
          top:      "32px"
          left:     "0px"
          z-index:  "-100"
      language: en
    geocoder:
      class: "Ivory\GoogleMapBundle\Model\Services\Geocoding\Geocoder"
      provider:
        class: "Ivory\GoogleMapBundle\Model\Services\Geocoding\\Provider"
        api_key: ~
        locale: en
      adapter: "Geocoder\HttpAdapter\BuzzHttpAdapter" 
################################################################################
## PUGX Multi User
################################################################################
parameters:
    pugx_user_discriminator_parameters:
        classes:
            faculty:
                entity: Scss\FacilityBundle\Entity\Faculty
                registration: Scss\FacilityBundle\Form\Type\RegistrationFacultyFormType
                profile: Scss\FacilityBundle\Form\Type\ProfileFacultyFormType
            passel_leader:
                entity: Scss\OrganizationBundle\Entity\PasselLeader
                registration: Scss\OrganizationBundle\Form\Type\RegistrationPasselLeaderFormType
                profile: Scss\OrganizationBundle\Form\Type\ProfilePasselLeaderFormType
            attendee:
                entity: Scss\OrganizationBundle\Entity\Attendee
                registration: Scss\OrganizationBundle\Form\Type\RegistrationAttendeeFormType
                profile: Scss\OrganizationBundle\Form\Type\ProfileAttendeeFormType
