scss_attribute:
    resource: "@SCSSAttributeBundle/Controller/"
    type:     annotation
    prefix:   /

scss_address:
    resource: "@SCSSAddressBundle/Controller/"
    type:     annotation
    prefix:   /

scss_course:
    resource: "@SCSSCourseBundle/Controller/"
    type: annotation
    prefix: /courses

scss_enrollment:
    resource: "@SCSSEnrollmentBundle/Controller/"
    type: annotation
    prefix: /enrollments

scss_facility:
    resource: "@SCSSFacilityBundle/Controller/"
    type: annotation
    prefix: /facilities

scss_organization:
    resource: "@SCSSOrganizationBundle/Controller/"
    type: annotation
    prefix: /organizations

scss_passel:
    resource: "@SCSSPasselBundle/Controller/"
    type: annotation
    prefix: /passels

scss_report:
    resource: "@SCSSReportBundle/Controller/"
    type: annotation
    prefix: /reports

scss_user:
    resource: "@SCSSUserBundle/Controller/"
    type: annotation
    prefix: /

about:
    pattern: /about
    defaults: { _controller: SCSSUserBundle:User:AboutSCSS }

contact:
    pattern: /contact
    defaults: { _controller: SCSSUserBundle:User:ContactSCSS }

fos_user_security_login:
    pattern: /signin
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    pattern: /signin-check
    defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    pattern: /signout
    defaults: { _controller: FOSUserBundle:Security_logout }

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /signup

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

_imagine:
    resource: .
    type:     imagine
