# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
homepage:
    pattern: /
    defaults: { _controller: ScssUserBundle:User:index }
help:
    pattern: /help
    defaults: { _controller: ScssUtilityBundle:Help:index }
help_specific:
    pattern: /help/{subject}
    defaults: { _controller: ScssUtilityBundle:Help:show }
settings:
    pattern: /account-settings
    defaults: { _controller: ScssUserBundle:AccountSettings:index }
about:
    pattern: /about
    defaults: { _controller: ScssUtilityBundle:About:index }
contact:
    pattern: /contact
    defaults: { _controller: ScssUtilityBundle:Contact:index }


# By Region
organization_by_region:
    pattern: /region/{slug}/organizations
    defaults: { _controller: ScssOrganizationBundle:Organization:region }  
group_by_region:
    pattern: /region/{slug}/groups
    defaults: { _controller: ScssOrganizationBundle:ScssGroup:region }
attendee_by_region:
    pattern: /region/{slug}/attendees
    defaults: { _controller: ScssOrganizationBundle:Attendee:region }
facility_by_region:
    pattern: /region/{region_slug}/facilities
    defaults: { _controller: ScssFacilityBundle:Facility:region }
class_by_region:
    pattern: /region/{slug}/classes
    defaults: { _controller: ScssCourseBundle:Class:region }
group_enrollment_by_region:
    pattern: /region/{slug}/group-enrollment
    defaults: { _controller: ScssFacilityBundle:GroupEnrollment:region }
week_by_region:
    pattern: /region/{slug}/weeks
    defaults: { _controller: ScssCourseBundle:Week:region }
# By Facility
department_by_facility:
    pattern: /region/{region_slug}/facility/{facility_slug}/departments
    defaults: { _controller: ScssFacilityBundle:Department:facility }
faculty_by_facility:
    pattern: /region/{region_slug}/facility/{facility_slug}/faculty
    defaults: { _controller: ScssFacilityBundle:Faculty:facility }
faculty_quarters_by_facility:
    pattern: /region/{region_slug}/facility/{facility_slug}/quarters/faculty
    defaults: { _controller: ScssFacilityBundle:FacultyQuarters:facility }
group_quarters_by_facility:
    pattern: /region/{region_slug}/facility/{facility_slug}/quarters/group
    defaults: { _controller: ScssFacilityBundle:GroupQuarters:facility }
class_by_facility:
    pattern: /region/{region_slug}/facility/{facility_slug}/classes
    defaults: { _controller: ScssCourseBundle:ScssClass:facility }
attendee_enrollment_by_facility:
    pattern: /region/{region_slug}/facility/{facility_slug}/attendee-enrollment
    defaults: { _controller: ScssCourseBundle:AttendeeEnrollment:facility }
group_enrollment_by_facility:
    pattern: /region/{region_slug}/facility/{facility_slug}/group-enrollment
    defaults: { _controller: ScssFacilityBundle:GroupEnrollment:facility }
week_by_facility:
    pattern: /region/{region_slug}/facility/{facility_slug}/weeks
    defaults: { _controller: ScssCourseBundle:Week:facility }
period_by_facility:
    pattern: /region/{region_slug}/facility/{facility_slug}/periods
    defaults: { _controller: ScssCourseBundle:Period:facility }
# By Group
subgroup_by_group:
    pattern: /region/{region_slug}/group/{group_slug}/subgroups
    defaults: { _controller: ScssOrganizaitonBundle:SubGroup:group }
attendee_by_group:
    pattern: /region/{region_slug}/group/{group_slug}/attendees
    defaults: { _controller: ScssOrganizationBundle:Attendee:group }
attendee_enrollment_by_group:
    pattern: /region/{region_slug}/group/{group_slug}/attendee-enrollment
    defaults: { _controller: ScssCourseBundle:AttendeeEnrollment:group }
group_enrollment_by_group:
    pattern: /region/{region_slug}/group/{grop_slug}/group-enrollment
    defaults: { _controller: ScssFacilityBundle:GroupEnrollment:group }
# By SubGroup
attendee_by_subgroup:
    pattern: /region/{region_slug}/group/{group_slug}/subgroup/{subgroup_slug}/attendees
    defaults: { _controller: ScssOrganizationBundle:Attendee:subgroup }
# By Week
period_by_Week:
    pattern: /region/{region_slug}/facility/{facility_slug}/week/{week_slug}/periods
    defaults: { _controller: ScssCourseBundle:Period:week }
class_by_week:
    pattern: /region/{region_slug}/facility/{facility_slug}/week/{week_slug}/classes
    defaults: { _controller: ScssCourseBundle:ScssClass:week }
attendee_enrollment_by_week:
    pattern: /region/{region_slug}/facility/{facility_slug}/week/{week_slug}/attendee-enrollment
    defaults: { _controller: ScssCourseBundle:AttendeeEnrollment:week }
# By Period
class_by_period:
    pattern: /region/{region_slug}/facility/{facility_slug}/week/{week_slug}/period/{period_slug}/classes
    defaults: { _controller: ScssCourseBundle:ScssClass:period }
attendee_enroll_by_period:
    pattern: /region/{region_slug}/facility/{facility_slug}/week/{week_slug}/period/{period_slug}/attendee-enrollment
    defaults: { _controller: ScssCourseBundle:AttendeeEnrollment:period }
# By Organization
facility_by_organilzation:
    pattern: /organization/facilities
    defaults: { _controller: ScssFacilityBundle:Facility:organization }
group_by_organization:
    pattern: /organization/groups
    defaults: { _controller: ScssOrganizationBundle:ScssGroup:organization }
# By Course:
attendee_by_course:
    pattern: /course/attendee-enrollment
    defaults: { _controller: ScssCourseBundle:AttendeeEnrollment:course }
facility_by_course:
    pattern: /course/facilities
    defaults: { _controller: ScssFacilityBundle:Facility:course }
class_by_course:
    pattern: /course/classes
    defaults: { _controller: ScssCourseBundle:ScssClass:course }
week_by_course:
    pattern: /course/weeks
    defaults: { _controller: ScssCourseBundle:Week:course }
# By Department
faculty_by_department:
    pattern: /region/{region_slug}/facility/{facility_slug}/department/{department_slug}/faculty
    defaults: { _controller: ScssFacilityBundle:Faculty:deparment }
class_by_department:
    pattern: /region/{region_slug}/facility/{facility_slug}/department/{department_slug}/classes
    defaults: { _controller: ScssCourseBundle:ScssClass:department }
# Show
region_show:
    pattern: /region/{region_slug}
    defaults: { _controller: ScssGeographyBundle:Region:show }  
facility_show:
    pattern: /region/{region_slug}/facility/{facililty_slug}
    defaults: { _controller: ScssFacilityBundle:Facility:show }  
department_show:
    pattern: /region/{region_slug}/facility/{facility_slug}/department/{department_slug}
    defaults: { _controller: ScssFacilityBundle:Department:show }  
faculty_quarters_show:
    pattern: /region/{region_slug}/facility/{facility_slug}/quarters/faculty/{faculty_quarters_slug}
    defaults: { _controller: ScssFacilityBundle:FacultyQuarters:show }  
group_quarters_show:
    pattern: /region/{region_slug}/facility/{facility_slug}/quarters/group/{group_quarters_slug}
    defaults: { _controller: ScssFacilityBundle:GroupQuarters:show }  
faculty_show:
    pattern: /region/{region_slug}/facility/{facility_slug}/faculty/{faculty_slug}
    defaults: { _controller: ScssFacilityBundle:Faculty:show }  
organization_show:
    pattern: /organization/{orgranization_slug}
    defaults: { _controller: ScssOrganizationBundle:Organizaiton:show }  
group_show:
    pattern: /region/{region_slug}/group/{group_slug}/
    defaults: { _controller: ScssOrganizationBundle:ScssGroup:show }  
subgroup_show:
    pattern: /region/{region_slug}/group/{group_slug}/subgroup/{subgroup}
    defaults: { _controller: ScssOrganizationBundle:SubGroup:show }  
attendee_show:
    pattern: /region/{region_slug}/group/{group_slug}/subgroup/{subgroup}/attendee/{attendee_slug}
    defaults: { _controller: ScssOrganizationBundle:Attendee:show }  
attendee_enrollment_show:
    pattern: /region/{region_slug}/facility/{facility_slug}/week/{week_slug}/attendee-enrollment
    defaults: { _controller: ScssCourseBundle:AttendeeEnrollment:show }  
group_enrollment_show:
    pattern: /region/{region_slug}/facility/{facility_slug}/week/{week_slug}/group-enrollment
    defaults: { _controller: ScssFacilityBundle:GroupEnrollment:show }  
course_show:
    pattern: /course/{course_slug}
    defaults: { _controller: ScssCourseBundle:Course:show }  
class_show:
    pattern: /region/{region_slug}/facility/{facility_slug}/week/{week_slug}/class/{class_slug}
    defaults: { _controller: ScssCourseBundle:ScssClass:show }  
week_show:
    pattern: /region/{region_slug}/facility/{facility_slug}/week/{week_Slug}
    defaults: { _controller: ScssCourseBundle:Week:show }  
period_show:
    pattern: /region/{region_slug}/facility/{facility_slug}/week/{week_slug}/period/{period_slug}
    defaults: { _controller: ScssCourseBundle:Period:show }  
# New 
region_new:
    pattern: /regions/new
    defaults: { _controller: ScssGeographyBundle:Region:new }    
facility_new:
    pattern: /region/{region_slug}/facility/{facility_slug}/new
    defaults: { _controller: ScssFacilityBundle:Facility:new }    
department_new:
    pattern: /region/{region_slug}/facility/{facility_slug}/departments/new
    defaults: { _controller: ScssFacilityBundle:Department:new }    
faculty_quarters_new:
    pattern: /region/{region_slug}/facility/{facility_slug}/quarters/faculty/new
    defaults: { _controller: ScssFacilityBundle:FacultyQuarters:new }    
group_quarters_new:
    pattern: /region/{region_slug}/facility/{facility_slug}/quarters/group/new
    defaults: { _controller: ScssFacilityBundle:GroupQuarters:new }    
faculty_new:
    pattern: /region/{region_slug}/facility/{facility_slug}/faculty/new
    defaults: { _controller: ScssFacilityBundle:Facility:new }    
organization_new:
    pattern: /organization/new
    defaults: { _controller: ScssOrganizationBundle:Organization:new }    
group_new:
    pattern: /region/{region_slug}/group/new
    defaults: { _controller: ScssOrganizationBundle:ScssGroup:new }    
subgroup_new:
    pattern: /region/{region_slug}/group/{group_slug}/subgroup/new
    defaults: { _controller: ScssOrganizationBundle:SubGroup:new }    
attendee_new:
    pattern: /region/{region_slug}/group/{group_slug}/attendees/new
    defaults: { _controller: ScssOrganizationBundle:Attendee:new }    
course_new:
    pattern: /course/new
    defaults: { _controller: ScssCourseBundle:Course:new }    
class_new:
    pattern: /region/{region_slug}/facility/{facility_slug}/classes/new
    defaults: { _controller: ScssCourseBundle:ScssClass:new }    
week_new:
    pattern: /region/{region_slug}/facility/{facility_slug}/week/new
    defaults: { _controller: ScssCourseBundle:Week:new }    
period_new:  
    pattern: /region/{region_slug}/facility/{facility_slug}/week/{week_slug}/period/new
    defaults: { _controller: ScssCourseBundle:Period:new }    
# Index
region:
    pattern: /regions
    defaults: { _controller: ScssGeographyBundle:Region:index }  
facility:
    pattern: /facilities
    defaults: { _controller: ScssFacilityBundle:Facility:index }  
department:
    pattern: /departments
    defaults: { _controller: ScssFacilityBundle:Department:index }  
faculty_quarters:
    pattern: /quarters/faculty
    defaults: { _controller: ScssFacilityBundle:FacultyQuarters:index }  
group_quarters:
    pattern: /quarters/group
    defaults: { _controller: ScssFacilityBundle:GroupQuraters:index }  
faculty:
    pattern: /faculty
    defaults: { _controller: ScssFacilityBundle:Faculty:index }  
organization:
    pattern: /organizations
    defaults: { _controller: ScssOrganizationBundle:Organization:index }  
group:
    pattern: /groups
    defaults: { _controller: ScssOrganizationBundle:ScssGroup:index }  
subgroup:
    pattern: /subgroups
    defaults: { _controller: ScssOrganizationBundle:SubGroup:index }  
attendee:
    pattern: /attendees
    defaults: { _controller: ScssOrganizationBundle:Attendee:index }  
attendee_enrollment:
    pattern: /attendee-enrollment
    defaults: { _controller: ScssCourseBundle:AttendeeEnrollment:index }  
group_enrollment:
    pattern: /group-enrollment
    defaults: { _controller: ScssFacilityBundle:GroupEnrollment:index }  
course:
    pattern: /courses
    defaults: { _controller: ScssCourseBundle:Course:index }  
class:
    pattern: /classes
    defaults: { _controller: ScssCourseBundle:ScssClass:index }  
week:
    pattern: /weeks
    defaults: { _controller: ScssCourseBundle:Week:index }  
period:
    pattern: /periods
    defaults: { _controller: ScssCourseBundle:Period:index }  