scss_utility:
    resource: "@SCSSUtilityBundle/Resources/config/routing.yml"
    prefix:   /

scss_user_security:
    resource: "@ScssUserBundle/Resources/config/routing/security.yml"
scss_user_signup:
    resource: "@ScssUserBundle/Resources/config/routing/signup.yml"
    prefix: /signup
enrollment:
    resource: "@ScssEnrollmentBundle/Resources/config/routing/routing.yml"
    prefix: /
organizaiton:
    resource: "@ScssOrganizationBundle/Resources/config/routing/routing.yml"
    prefix: /
course:
    resource: "@ScssCourseBundle/Resources/config/routing/routing.yml"
    prefix: /
facility:
    resource: "@ScssFacilityBundle/Resources/config/routing/routing.yml"
    prefix: /
passel:
    resource: "@ScssPasselBundle/Resources/config/routing/routing.yml"
    prefix: /
report:
    resource: "@ScssReportBundle/Resources/config/routing/routing.yml"
    prefix: /    
#misc:
#    resource: "@ScssUtilityBundle/Resources/config/routing/routing.yml"
#    prefix: /
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile  
homepage:
    pattern: /
    defaults: { _controller: ScssUserBundle:User:index }
dashboard:
    pattern: /dashboard
    defaults: { _controller: ScssUserBundle:User:index }
about:
    pattern: /about
    defaults: { _controller: ScssUserBundle:User:about }
help:
    pattern: /help
    defaults: { _controller: ScssUserBundle:User:help }
contact:
    pattern: /contact
    defaults: { _controller: ScssUserBundle:User:contact }
attendee_registration:
    pattern:  /signup/attendee
    defaults: { _controller: ScssUserBundle:RegistrationAttendee:register }
passel_leader_registration:
    pattern:  /signup/passel-leader
    defaults: { _controller: ScssUserBundle:RegistrationPasselLeader:register }    
faculty_registration:
    pattern: /signup/faculty
    defaults: { _controller: ScssUserBundle:RegistrationFaculty:register }