hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
scss_user_security:
    resource: "@ScssUserBundle/Resources/config/routing/security.yml"
scss_user_signup:
    resource: "@ScssUserBundle/Resources/config/routing/signup.yml"
    prefix: /signup
organizaiton:
    resource: "@ScssOrganizationBundle/Resources/config/routing/routing.yml"
    prefix: /
course:
    resource: "@ScssCourseBundle/Resources/config/routing/routing.yml"
    prefix: /
facility:
    resource: "@ScssFacilityBundle/Resources/config/routing/routing.yml"
    prefix: /
geography:
    resource: "@ScssGeographyBundle/Resources/config/routing/routing.yml"
    prefix: /
misc:
    resource: "@ScssUtilityBundle/Resources/config/routing/routing.yml"
    prefix: /
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile  
homepage:
    pattern: /
    defaults: { _controller: ScssUserBundle:User:index }
dashboard:
    pattern: /dashboard
    defaults: { _controller: ScssUserBundle:User:index }