
services:
################################################################################
## Pagerfanta ##################################################################
################################################################################
    pagerfanta.view.default:
        class: Pagerfanta\View\DefaultView
        public: false
        tags: [{ name: pagerfanta.view, alias: default }]

################################################################################
## KnP Menu ####################################################################
################################################################################
    scss_menu.menu_builder:
        class: SCSS\UtilityBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    scss_menu.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: scss_menu.menu_builder
        factory_method: createMainMenu
        arguments: [ "@request", "@service_container" ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    scss_menu.menu.nonauth:
        class: Knp\Menu\MenuItem
        factory_service: scss_menu.menu_builder
        factory_method: createNonAuthMenu
        arguments: [ "@request" ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: nonauth }
