###############################################################################
## Organization
###############################################################################
organizations:
    pattern: /organizations
    defaults: { _controller: ScssOrganizationBundle:Organization:index }
organization_show:
    pattern: /organizations/{organization}
    defaults: { _controller: ScssOrganizationBundle:Organization:show }
organization_new:
    pattern: /organizations/new
    defaults: { _controller: ScssOrganizationBundle:Organization:new }    
organization_edit:
    pattern: /organizations/{organization}/edit
    defaults: { _controller: ScssOrganizationBundle:Organization:edit }    

###############################################################################
## Council
###############################################################################
councils:
    pattern: /councils
    defaults: { _controller: ScssOrganizationBundle:Council:index }    
councils_by_organization:
    pattern: /organizations/{organization}/councils
    defaults: { _controller: ScssOrganizationBundle:Council:organization }    
councils_show:
    pattern: /councils/{council}
    defaults: { _controller: ScssOrganizationBundle:Council:show }    
councils_new:
    pattern: /councils/new
    defaults: { _controller: ScssOrganizationBundle:Council:new }    
councils_edit:
    pattern: /councils/{council}/edit
    defaults: { _controller: ScssOrganizationBundle:Council:edit }    