parameters:
#    scss_utility.example.class: SCSS\UtilityBundle\Example

services:
#    scss_utility.example:
#        class: %scss_utility.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
