help:
    pattern: /help
    defaults: { _controller: ScssUtilityBundle:Help:index }
help_specific:
    pattern: /help/{subject}
    defaults: { _controller: ScssUtilityBundle:Help:show }
settings:
    pattern: /account-settings
    defaults: { _controller: ScssUserBundle:AccountSettings:index }
about:
    pattern: /about
    defaults: { _controller: ScssUtilityBundle:About:index }
contact:
    pattern: /contact
    defaults: { _controller: ScssUtilityBundle:Contact:index }