parameters:
#    SCSS_course.example.class: SCSS\CourseBundle\Example

services:
#    SCSS_course.example:
#        class: %SCSS_course.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
