parameters:
#    scss_passel.example.class: Scss\PasselBundle\Example

services:
#    scss_passel.example:
#        class: %scss_passel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
