# config/assets_manager.yml
packages:
  jquery:
    js:  libs/jquery.latest.js
  jquery-ui:
    import: jquery
    js: libs/jquery-ui.latest.js
    css: jquery-ui/jquery-ui-1.8.16.custom.css
  layout:
    css: [scss.css.php,header.css.php,footer.css.php]
    js: scss.js
# forms
#######
  form:
    import: layout
    css: form.css.php
  colorpicker:
    import: form
    css: colorpicker.css
    js: [libs/colorpicker/colorpicker.js,scss.form.js]
  login:
    import: [form,jquery-ui]
    css: login.css.php
  signup:
    import: [form,jquery-ui]
  data-table:
    import: jquery-ui
    css: datatable.css.php
  grid:
    import: data-table
    css: datagrid.css.php
    js: scss.grid.js
# pages
#######
  dashboard:
    import: [layout,jquery-ui,data-table]
    css: dashboard.css.php
    js: mylibs/dashboard.js
  search:
    import: [layout,jquery-ui]
    css: search.css.php
    js: mylibs/scss.search.js
  about:
    import: layout
  contact:
    import: layout
# modules
#########
  geo: # country, zone
    import: layout
  district:
    import: layout
  troop: 
    import: layout
  patrol:
    import: layout
  scout:
    import: layout
  enroll: # scoutEnrollment, troopRegistration
    import: form
  camp: # camp, area, campsite
    import: layout
  time: # week, period
    import: layout
  class: # course, class
    import: layout
    css: class.css.php
#  badge: # MB, req
#  staff: # staff, cabin
