scout:
  class: sfDoctrineRouteCollection
  options:
    model: ScssScout
    module: scout
    prefix_path: /troops/:district_slug/:troop_slug/scouts
    column: scout_slug
scouts_by_troop:
  url: /troops/:district_slug/:troop_slug/scouts
  class:   sfDoctrineRoute
  options: { model: JobeetJob, type: object }
  param: { module: scout, action: index }
scouts_by_patrol:
  url: /troops/:district_slug/:troop_slug/:patrol_slug/scouts
  param: { module: scout, action: index }
scouts_by_class:
  url: /camps/:camp_slug/:week_slug/:period_slug/:class_slug/scouts
  params: { module: scout, action: index }
