passel_quarters:
    pattern: /passel-quarters
    defaults: { _controller: ScssFacilityBundle:PasselQuarters:index }
passel_quarters_by_facility:
    pattern: /facilities/{facility}/passel-quarters
    defaults: { _controller: ScssFacilityBundle:PasselQuarters:index }
passel_quarters_show:
    pattern: /facilities/{facility}/passel-quarters/{passel-quarters}
    defaults: { _controller: ScssFacilityBundle:PasselQuarters:show }
    
faculty_quarters:
    pattern: /faculty-quarters
    defaults: { _controller: ScssFacilityBundle:FacultyQuarters:index }
faculty_quarters_by_facility:
    pattern: /facilities/{facility}/faculty-quarters
    defaults: { _controller: ScssFacilityBundle:FacultyQuarters:index }
faculty_quarters_show:
    pattern: /facilities/{facility}/faculty-quarters/{faculty-quarters}
    defaults: { _controller: ScssFacilityBundle:FacultyQuarters:show }    
